accounts/urls.py
from accounts import views
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from accounts.forms import (
    LoginForm,
    UserPasswordChangeForm,
    UserPasswordResetForm,
)

app_name = 'accounts'

urlpatterns = [
    path(
        'activate/<uidb64>/<token>/',
        views.Activate.as_view(),
        name='activate'
    ),
    path(
        'login', views.UserLoginView.as_view(
            form_class=LoginForm
        ), name='login'
    ),
    path(
        'logout', auth_views.LogoutView.as_view(
            template_name='registration/logged_out.html'
        ), name='logout'
    ),
    path(
        'register',
        views.RegistrationFormView.as_view(),
        name='register'
    ),
    path(
        'password/change',
        views.UserPasswordChangeView.as_view(
            form_class=UserPasswordChangeForm
        ),
        name='password_change'
    ),
    path(
        'password/reset',
        views.UserPasswordResetView.as_view(
            form_class=UserPasswordResetForm
        ), name='password_reset'
    ),
    path(
        'password/reset/<uidb64>/<token>/confirm/',
        views.UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'profile/<uuid:unique_id>/',
        views.UserProfileView.as_view(
            template_name='accounts/profile.html'
        ), name='profile'
    ),
    path(
        'profile/<uuid:unique_id>/update/',
        views.UserProfileUpdateView.as_view(
            template_name='accounts/user_profile_update_form.html'
        ), name='profile_update'
    ),
    path(
        'registration/complete/',
        TemplateView.as_view(
            template_name='registration/registration_complete.html'
        ), name='registration_complete'
    )
]

core/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

templates/partials/navbar.html
{% load fontawesome_5 %}

<nav class="mb-5 navbar navbar-expand-lg navbar-light bg-light border">
    <span class="navbar-brand mb-0 h1">Brand</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" style="text-decoration: none; color: black;" 
                    href="{% url 'accounts:logout' %}">
                    Logout {% fa5_icon 'sign-out-alt' 'fas' %}
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" style="text-decoration: none; color: black;"  
                    href="{% url 'accounts:profile' request.user.unique_id %}">
                        ({{request.user}})
                </a>
            </li>
             
            {% else %}
            <li class="nav-item">
                <a class="nav-link" style="text-decoration: none; color: black;" 
                    href="{% url 'accounts:register' %}">
                    {% fa5_icon 'profile' 'fas' %}
                    Register
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="text-decoration: none; color: black;" 
                    href="{% url 'accounts:login' %}">
                    {% fa5_icon 'sign-in-alt' 'fas' %}
                    Login
                </a> 
            </li>     
            {% endif %}
        </ul>
    </div>
</nav>